[package]
authors = ["_Pyramid", "pyramid-songs@protonmail.com"]
edition = "2018"
name = "links-exercise"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "exercise"

[dependencies]
derive_more = "0"
serde = "1"

hdk = "0.0.108"
chrono = "0.4.19"